
version: 2

models:
  - name: my_first_dbt_model
    description: "A starter dbt model"
    columns:
      - name: id
        description: "The primary key for this table"
        tests:
          - unique
          - accepted_values:
              values: [1, 2]
              quote: false

  - name: my_second_dbt_model
    description: "A starter dbt model"
    columns:
      - name: id
        description: "The primary key for this table"
        tests:
          - unique
          - not_null
          - relationships:
              to: ref('my_first_dbt_model')
              field: id

  - name: snowflake_customer_purchases
    description: "Total purchases for each customer"
    columns:
      - name: c_custkey
        description: "The primary key for this table"
        tests:
          - unique
          - not_null

  - name: cumulative_orders_by_date
    description: "cumulative sales for the order date"
    columns:
      - name: date_value
        description: "The dates"


  - name: dates
    description: "this is an incremental table"
    columns:
      - name: d_date
        description: "The dates"

  - name: incremental_time

  - name: playing_with_tests
    description: "Play with some tests"
    columns:
      - name: c_custkey
        description: "The primary key for this table"
        tests:
          - unique
          - not_null
      - name: c_mktsegment
        tests:
          - accepted_values:
              values: [ 'BUILDING','AUTOMOBILE', 'MACHINERY', 'HOUSEHOLD', 'FURNITURE' ]

sources:
  - name: sample
    database: SNOWFLAKE_SAMPLE_DATA
    schema: TPCH_SF1
    tables:
      - name: customer
        columns:
          - name: c_custkey
            tests:
              - unique
              - not_null
      - name: orders
